#
# This file is part of Ardix.
# Copyright (c) 2020, 2021 Felix Kopp <owo@fef.moe>.
#
# Ardix is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ardix is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

ARDIX_LIB_PWD := $(PWD)/lib

ARDIX_SOURCES += \
	$(ARDIX_LIB_PWD)/ctype.c \
	$(ARDIX_LIB_PWD)/errno.c \
	$(ARDIX_LIB_PWD)/list.c \
	$(ARDIX_LIB_PWD)/malloc.c \
	$(ARDIX_LIB_PWD)/string.c \
	$(ARDIX_LIB_PWD)/unistd.c
